# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
use_frameworks!

target 'MovieApp' do
    #UI
    pod 'JGProgressHUD'
    pod 'UIScrollView-InfiniteScroll', '~> 1.1.0'
    
    #NETWORKING
    pod 'Alamofire', '~> 4.7'
    pod 'SDWebImage'
    
    #DATABASE
    pod 'RealmSwift'
    
    #ANALITICS/EVENTS/CRASH
    pod 'Fabric'
    pod 'Crashlytics'
end

target 'MovieAppTests' do
    inherit! :search_paths
    # Pods for testing
end
