# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
use_frameworks!

target 'MovieApp' do
    pod 'Alamofire', '~> 4.7'
    pod 'SDWebImage'
    pod 'RealmSwift'
    
    pod 'Fabric'
    pod 'Crashlytics'
end

target 'MovieAppTests' do
    inherit! :search_paths
    # Pods for testing
end
