# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MovieApp' do
  use_frameworks!

  pod 'Alamofire', '~> 4.0.0'

  target 'MovieAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
