# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GetMovieApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GetMovieApp
  pod 'Alamofire'

  target 'GetMovieAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GetMovieAppUITests' do
    # Pods for testing
  end

end
