# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'movs' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Nuke', '~> 8.0'

  target 'movsTests' do
    inherit! :search_paths
    # Pods for testing
  end
  
end

target 'movsUITests' do
  inherit! :search_paths
  
end
