# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'movieFinder' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for movieFinder
  pod 'Alamofire', '5.6.2'
  pod 'SwiftLint', '0.49.1'
  pod 'RealmSwift', '10.30.0'

  target 'movieFinderTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'movieFinderUITests' do
    # Pods for testing
  end

end
