# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'moviewsApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for moviewsApp

pod 'Alamofire', '~> 4.4'
pod 'SwiftyJSON', '~> 4.0'
pod 'Toast-Swift', '~> 3.0.1'

  target 'moviewsAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'moviewsAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
