# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MoviesAppIOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MoviesAppIOS
  pod 'Alamofire'

  target 'MoviesAppIOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MoviesAppIOSUITests' do
    # Pods for testing
  end

end
