# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def common_pods
  pod 'Alamofire', '~> 4.5'
end

target 'Concrete-Movies' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Concrete-Movies
  common_pods

  target 'Concrete-MoviesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Concrete-MoviesUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
