# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'movie-app-hsa' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for movie-app-hsa
  pod 'Alamofire'
  pod 'SwiftLint'

  target 'movie-app-hsaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'movie-app-hsaUITests' do
    # Pods for testing
  end

end
