# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'InformationMovies' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for InformationMovies
  pod 'Alamofire'
  pod 'AlamofireImage'

  target 'InformationMoviesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'InformationMoviesUITests' do
    # Pods for testing
  end

end
