# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Movies' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SwiftyJSON'
  pod 'Alamofire'
  pod 'IQKeyboardManagerSwift'
  pod 'SDWebImage', '~> 5.0'

end
