# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'Movies' do
  use_frameworks!
  inhibit_all_warnings!

  pod 'SwiftyJSON'
  pod 'Alamofire'
  pod 'IQKeyboardManagerSwift'
  pod 'SDWebImage', '~> 5.0'
  pod 'lottie-ios'

end
