# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'concreteMovieData' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for concreteMovieData

  target 'concreteMovieDataTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'concreteMovieDataUITests' do
    inherit! :search_paths
    # Pods for testing
  end
pod 'AlamofireObjectMapper', '~> 5.2'
end
