# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ConcreteIOsRecruit' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ConcreteIOsRecruit
  pod 'Alamofire', '~> 4.7'
  pod 'lottie-ios'
  pod 'Kingfisher', '~> 4.0'

  target 'ConcreteIOsRecruitTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ConcreteIOsRecruitUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
