# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'TestProject' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'Kingfisher', '~> 4.0' 
  pod 'SVProgressHUD'

  # Pods for TestProject

  target 'TestProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestProjectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
